#!/usr/bin/python
# ================================
# (C)2022 Dmytro Holub
# heap3d@gmail.com
# --------------------------------
# modo python
# EMAG
# h3d_item_replace_tools kit constants

USER_VAL_NAME_TEMPLATE_MESH = 'h3d_pt_template_mesh'
USER_VAL_NAME_CENTER_IDX = 'h3d_pt_template_poly_center_idx'
USER_VAL_NAME_CENTER_AREA_PERC = 'h3d_pt_center_area_percent'
USER_VAL_NAME_AREA_THRESHOLD = 'h3d_pt_center_area_threshold'
USER_VAL_NAME_USE_LARGEST_POLY = 'h3d_pt_use_largest_poly'
USER_VAL_NAME_SOURCE_NAME = 'h3d_pt_source_name'
USER_VAL_NAME_POLY_TRIPLE = 'h3d_pt_poly_triple'
USER_VAL_NAME_SCALE_X = 'h3d_pt_scale_x'
USER_VAL_NAME_SCALE_Y = 'h3d_pt_scale_y'
USER_VAL_NAME_SCALE_Z = 'h3d_pt_scale_z'
USER_VAL_NAME_LOCK_XYZ = 'h3d_pt_lock_xyz'
USER_VAL_NAME_LOCK_XYZ_ORDER = 'h3d_pt_lock_xyz_order'
USER_VAL_NAME_SAVE_LOG = 'h3d_pt_save_log'
USER_VAL_NAME_ANGLE_AXIS = 'h3d_pt_angle_axis'
USER_VAL_NAME_ANGLE_STEP = 'h3d_pt_angle_step'
USER_VAL_NAME_COPLANAR_ANGLE = 'h3d_pt_coplanar_angle'
USER_VAL_NAME_COPLANAR_RANGE = 'h3d_pt_coplanar_range'

USER_VAL_NAME_SEARCH_DIST = 'h3d_sumt_search_dist'
USER_VAL_NAME_GROUP_SIMILAR = 'h3d_sumt_group_similar'
USER_VAL_NAME_GROUP_EQUAL = 'h3d_sumt_group_equal'
USER_VAL_NAME_MERGE_CLOSEST = 'h3d_sumt_merge_closest'
USER_VAL_NAME_LARGEST_ROT = 'h3d_sumt_largest_rot'
USER_VAL_NAME_LARGEST_POS = 'h3d_sumt_largest_pos'
USER_VAL_NAME_DO_BOUNDING_BOX_X = 'h3d_sumt_do_bounding_box_x'
USER_VAL_NAME_DO_BOUNDING_BOX_Y = 'h3d_sumt_do_bounding_box_y'
USER_VAL_NAME_DO_BOUNDING_BOX_Z = 'h3d_sumt_do_bounding_box_z'
USER_VAL_NAME_DO_CENTER_POS_X = 'h3d_sumt_do_center_pos_x'
USER_VAL_NAME_DO_CENTER_POS_Y = 'h3d_sumt_do_center_pos_y'
USER_VAL_NAME_DO_CENTER_POS_Z = 'h3d_sumt_do_center_pos_z'
USER_VAL_NAME_DO_COM_POS_X = 'h3d_sumt_do_com_pos_x'
USER_VAL_NAME_DO_COM_POS_Y = 'h3d_sumt_do_com_pos_y'
USER_VAL_NAME_DO_COM_POS_Z = 'h3d_sumt_do_com_pos_z'
USER_VAL_NAME_DO_MESH_VOL = 'h3d_sumt_do_mesh_vol'
USER_VAL_NAME_BB_THRESHOLD_X = 'h3d_sumt_bb_threshold_x'
USER_VAL_NAME_BB_THRESHOLD_Y = 'h3d_sumt_bb_threshold_y'
USER_VAL_NAME_BB_THRESHOLD_Z = 'h3d_sumt_bb_threshold_z'
USER_VAL_NAME_CENTER_THRESHOLD_X = 'h3d_sumt_center_threshold_x'
USER_VAL_NAME_CENTER_THRESHOLD_Y = 'h3d_sumt_center_threshold_y'
USER_VAL_NAME_CENTER_THRESHOLD_Z = 'h3d_sumt_center_threshold_z'
USER_VAL_NAME_COM_THRESHOLD_X = 'h3d_sumt_com_threshold_x'
USER_VAL_NAME_COM_THRESHOLD_Y = 'h3d_sumt_com_threshold_y'
USER_VAL_NAME_COM_THRESHOLD_Z = 'h3d_sumt_com_threshold_z'
USER_VAL_NAME_VOL_THRESHOLD = 'h3d_sumt_vol_threshold'

TMP_GRP_NAME_BASE = '$h3d$ unmerge '
TMP_FOLDER_NAME = 'h3d_pt_replaced_items_to_delete'
GEO_SHAPE_SIMILAR_TYPE_NAME_BASE = '$h3d$ geo similar '
GEO_SHAPE_EQUAL_TYPE_NAME_BASE = '$h3d$ geo equal '
SELECTION_SET_BASE_NAME = '$delete$ h3d place tools'
DIV_LIT = '-'
